# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resp.proto',
  package='',
  serialized_pb=_b('\n\nresp.proto\"=\n\x04resp\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0b\n\x03\x62in\x18\x02 \x01(\x0c\x12\x0b\n\x03\x64lg\x18\x03 \x01(\t\x12\r\n\x05isEnd\x18\x04 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESP = _descriptor.Descriptor(
  name='resp',
  full_name='resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='resp.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bin', full_name='resp.bin', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dlg', full_name='resp.dlg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isEnd', full_name='resp.isEnd', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['resp'] = _RESP

resp = _reflection.GeneratedProtocolMessageType('resp', (_message.Message,), dict(
  DESCRIPTOR = _RESP,
  __module__ = 'resp_pb2'
  # @@protoc_insertion_point(class_scope:resp)
  ))
_sym_db.RegisterMessage(resp)


# @@protoc_insertion_point(module_scope)
