# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: req.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='req.proto',
  package='',
  serialized_pb=_b('\n\treq.proto\"V\n\x07\x61udio_m\x12\x11\n\taudioType\x18\x01 \x01(\t\x12\x12\n\nsampleRate\x18\x02 \x01(\r\x12\x13\n\x0bsampleBytes\x18\x03 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\r\"\xaf\x01\n\x07param_m\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0b\n\x03res\x18\x02 \x01(\t\x12\x11\n\tuseStream\x18\x03 \x01(\x08\x12\x0e\n\x06volume\x18\x04 \x01(\x02\x12\r\n\x05speed\x18\x05 \x01(\x02\x12\r\n\x05pitch\x18\x06 \x01(\x02\x12\x0b\n\x03\x65nv\x18\x07 \x01(\t\x12\x0e\n\x06semRes\x18\x08 \x01(\t\x12\x0f\n\x07\x65\x62nfRes\x18\t \x01(\t\x12\x1a\n\x05iType\x18\n \x01(\x0e\x32\x0b.iType_enum\":\n\x06\x64\x65sc_m\x12\x17\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x08.audio_m\x12\x17\n\x05param\x18\x02 \x01(\x0b\x32\x08.param_m\"G\n\x07\x65xtra_m\x12\x0c\n\x04hook\x18\x01 \x01(\t\x12\r\n\x05\x61ppId\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x03 \x01(\t\x12\r\n\x05token\x18\x04 \x01(\t\"l\n\x07payload\x12\x16\n\x03\x61\x63t\x18\x01 \x02(\x0e\x32\t.act_enum\x12\x0b\n\x03obj\x18\x02 \x01(\t\x12\x15\n\x04\x64\x65sc\x18\x03 \x01(\x0b\x32\x07.desc_m\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x17\n\x05\x65xtra\x18\x05 \x01(\x0b\x32\x08.extra_m**\n\x08\x61\x63t_enum\x12\t\n\x05START\x10\x00\x12\n\n\x06\x41PPEND\x10\x01\x12\x07\n\x03\x45ND\x10\x02*3\n\niType_enum\x12\x07\n\x03One\x10\x01\x12\x07\n\x03Two\x10\x02\x12\t\n\x05Three\x10\x03\x12\x08\n\x04\x46our\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ACT_ENUM = _descriptor.EnumDescriptor(
  name='act_enum',
  full_name='act_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPEND', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=522,
  serialized_end=564,
)
_sym_db.RegisterEnumDescriptor(_ACT_ENUM)

act_enum = enum_type_wrapper.EnumTypeWrapper(_ACT_ENUM)
_ITYPE_ENUM = _descriptor.EnumDescriptor(
  name='iType_enum',
  full_name='iType_enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='One', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Two', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Three', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Four', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=566,
  serialized_end=617,
)
_sym_db.RegisterEnumDescriptor(_ITYPE_ENUM)

iType_enum = enum_type_wrapper.EnumTypeWrapper(_ITYPE_ENUM)
START = 0
APPEND = 1
END = 2
One = 1
Two = 2
Three = 3
Four = 4



_AUDIO_M = _descriptor.Descriptor(
  name='audio_m',
  full_name='audio_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audioType', full_name='audio_m.audioType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampleRate', full_name='audio_m.sampleRate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sampleBytes', full_name='audio_m.sampleBytes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='audio_m.channel', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=99,
)


_PARAM_M = _descriptor.Descriptor(
  name='param_m',
  full_name='param_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='param_m.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='res', full_name='param_m.res', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='useStream', full_name='param_m.useStream', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='volume', full_name='param_m.volume', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='param_m.speed', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='param_m.pitch', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env', full_name='param_m.env', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='semRes', full_name='param_m.semRes', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ebnfRes', full_name='param_m.ebnfRes', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iType', full_name='param_m.iType', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=277,
)


_DESC_M = _descriptor.Descriptor(
  name='desc_m',
  full_name='desc_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='audio', full_name='desc_m.audio', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param', full_name='desc_m.param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=337,
)


_EXTRA_M = _descriptor.Descriptor(
  name='extra_m',
  full_name='extra_m',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hook', full_name='extra_m.hook', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appId', full_name='extra_m.appId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='deviceId', full_name='extra_m.deviceId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='extra_m.token', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=410,
)


_PAYLOAD = _descriptor.Descriptor(
  name='payload',
  full_name='payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='act', full_name='payload.act', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obj', full_name='payload.obj', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='desc', full_name='payload.desc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='payload.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra', full_name='payload.extra', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=520,
)

_PARAM_M.fields_by_name['iType'].enum_type = _ITYPE_ENUM
_DESC_M.fields_by_name['audio'].message_type = _AUDIO_M
_DESC_M.fields_by_name['param'].message_type = _PARAM_M
_PAYLOAD.fields_by_name['act'].enum_type = _ACT_ENUM
_PAYLOAD.fields_by_name['desc'].message_type = _DESC_M
_PAYLOAD.fields_by_name['extra'].message_type = _EXTRA_M
DESCRIPTOR.message_types_by_name['audio_m'] = _AUDIO_M
DESCRIPTOR.message_types_by_name['param_m'] = _PARAM_M
DESCRIPTOR.message_types_by_name['desc_m'] = _DESC_M
DESCRIPTOR.message_types_by_name['extra_m'] = _EXTRA_M
DESCRIPTOR.message_types_by_name['payload'] = _PAYLOAD
DESCRIPTOR.enum_types_by_name['act_enum'] = _ACT_ENUM
DESCRIPTOR.enum_types_by_name['iType_enum'] = _ITYPE_ENUM

audio_m = _reflection.GeneratedProtocolMessageType('audio_m', (_message.Message,), dict(
  DESCRIPTOR = _AUDIO_M,
  __module__ = 'req_pb2'
  # @@protoc_insertion_point(class_scope:audio_m)
  ))
_sym_db.RegisterMessage(audio_m)

param_m = _reflection.GeneratedProtocolMessageType('param_m', (_message.Message,), dict(
  DESCRIPTOR = _PARAM_M,
  __module__ = 'req_pb2'
  # @@protoc_insertion_point(class_scope:param_m)
  ))
_sym_db.RegisterMessage(param_m)

desc_m = _reflection.GeneratedProtocolMessageType('desc_m', (_message.Message,), dict(
  DESCRIPTOR = _DESC_M,
  __module__ = 'req_pb2'
  # @@protoc_insertion_point(class_scope:desc_m)
  ))
_sym_db.RegisterMessage(desc_m)

extra_m = _reflection.GeneratedProtocolMessageType('extra_m', (_message.Message,), dict(
  DESCRIPTOR = _EXTRA_M,
  __module__ = 'req_pb2'
  # @@protoc_insertion_point(class_scope:extra_m)
  ))
_sym_db.RegisterMessage(extra_m)

payload = _reflection.GeneratedProtocolMessageType('payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'req_pb2'
  # @@protoc_insertion_point(class_scope:payload)
  ))
_sym_db.RegisterMessage(payload)


# @@protoc_insertion_point(module_scope)
